// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: dragonboat.proto

package dbpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DragonboatService_Propose_FullMethodName         = "/dragonboat.v1.DragonboatService/Propose"
	DragonboatService_Read_FullMethodName            = "/dragonboat.v1.DragonboatService/Read"
	DragonboatService_StaleRead_FullMethodName       = "/dragonboat.v1.DragonboatService/StaleRead"
	DragonboatService_GetMembership_FullMethodName   = "/dragonboat.v1.DragonboatService/GetMembership"
	DragonboatService_AddReplica_FullMethodName      = "/dragonboat.v1.DragonboatService/AddReplica"
	DragonboatService_RemoveReplica_FullMethodName   = "/dragonboat.v1.DragonboatService/RemoveReplica"
	DragonboatService_TransferLeader_FullMethodName  = "/dragonboat.v1.DragonboatService/TransferLeader"
	DragonboatService_RequestSnapshot_FullMethodName = "/dragonboat.v1.DragonboatService/RequestSnapshot"
	DragonboatService_GetNodeHostInfo_FullMethodName = "/dragonboat.v1.DragonboatService/GetNodeHostInfo"
	DragonboatService_GetLeader_FullMethodName       = "/dragonboat.v1.DragonboatService/GetLeader"
	DragonboatService_HealthCheck_FullMethodName     = "/dragonboat.v1.DragonboatService/HealthCheck"
)

// DragonboatServiceClient is the client API for DragonboatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DragonboatService exposes the core NodeHost operations over gRPC.
// A grpc-gateway sidecar provides an identical REST/JSON surface
// on a separate HTTP listener with no extra handler code.
type DragonboatServiceClient interface {
	// Propose submits a serialised command to the specified Raft shard and
	// waits for it to be committed and applied (SyncPropose).
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error)
	// Read performs a linearisable read on the specified shard (SyncRead).
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// StaleRead performs a non-linearisable local read (lower latency).
	StaleRead(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// GetMembership returns the current membership of a shard.
	GetMembership(ctx context.Context, in *GetMembershipRequest, opts ...grpc.CallOption) (*GetMembershipResponse, error)
	// AddReplica adds a new voting replica to the shard (SyncRequestAddReplica).
	AddReplica(ctx context.Context, in *AddReplicaRequest, opts ...grpc.CallOption) (*AddReplicaResponse, error)
	// RemoveReplica removes a replica from the shard (SyncRequestDeleteReplica).
	RemoveReplica(ctx context.Context, in *RemoveReplicaRequest, opts ...grpc.CallOption) (*RemoveReplicaResponse, error)
	// TransferLeader requests a leadership transfer to another replica.
	TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error)
	// RequestSnapshot triggers an immediate snapshot of a shard.
	RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// GetNodeHostInfo returns status information for the local NodeHost.
	GetNodeHostInfo(ctx context.Context, in *NodeHostInfoRequest, opts ...grpc.CallOption) (*NodeHostInfoResponse, error)
	// GetLeader returns the current leader of the specified shard.
	GetLeader(ctx context.Context, in *GetLeaderRequest, opts ...grpc.CallOption) (*GetLeaderResponse, error)
	// HealthCheck returns OK when the NodeHost is alive and accepting requests.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type dragonboatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDragonboatServiceClient(cc grpc.ClientConnInterface) DragonboatServiceClient {
	return &dragonboatServiceClient{cc}
}

func (c *dragonboatServiceClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, DragonboatService_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, DragonboatService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) StaleRead(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, DragonboatService_StaleRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) GetMembership(ctx context.Context, in *GetMembershipRequest, opts ...grpc.CallOption) (*GetMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembershipResponse)
	err := c.cc.Invoke(ctx, DragonboatService_GetMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) AddReplica(ctx context.Context, in *AddReplicaRequest, opts ...grpc.CallOption) (*AddReplicaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddReplicaResponse)
	err := c.cc.Invoke(ctx, DragonboatService_AddReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) RemoveReplica(ctx context.Context, in *RemoveReplicaRequest, opts ...grpc.CallOption) (*RemoveReplicaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveReplicaResponse)
	err := c.cc.Invoke(ctx, DragonboatService_RemoveReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferLeaderResponse)
	err := c.cc.Invoke(ctx, DragonboatService_TransferLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, DragonboatService_RequestSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) GetNodeHostInfo(ctx context.Context, in *NodeHostInfoRequest, opts ...grpc.CallOption) (*NodeHostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeHostInfoResponse)
	err := c.cc.Invoke(ctx, DragonboatService_GetNodeHostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) GetLeader(ctx context.Context, in *GetLeaderRequest, opts ...grpc.CallOption) (*GetLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderResponse)
	err := c.cc.Invoke(ctx, DragonboatService_GetLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonboatServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DragonboatService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DragonboatServiceServer is the server API for DragonboatService service.
// All implementations must embed UnimplementedDragonboatServiceServer
// for forward compatibility.
//
// DragonboatService exposes the core NodeHost operations over gRPC.
// A grpc-gateway sidecar provides an identical REST/JSON surface
// on a separate HTTP listener with no extra handler code.
type DragonboatServiceServer interface {
	// Propose submits a serialised command to the specified Raft shard and
	// waits for it to be committed and applied (SyncPropose).
	Propose(context.Context, *ProposeRequest) (*ProposeResponse, error)
	// Read performs a linearisable read on the specified shard (SyncRead).
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// StaleRead performs a non-linearisable local read (lower latency).
	StaleRead(context.Context, *ReadRequest) (*ReadResponse, error)
	// GetMembership returns the current membership of a shard.
	GetMembership(context.Context, *GetMembershipRequest) (*GetMembershipResponse, error)
	// AddReplica adds a new voting replica to the shard (SyncRequestAddReplica).
	AddReplica(context.Context, *AddReplicaRequest) (*AddReplicaResponse, error)
	// RemoveReplica removes a replica from the shard (SyncRequestDeleteReplica).
	RemoveReplica(context.Context, *RemoveReplicaRequest) (*RemoveReplicaResponse, error)
	// TransferLeader requests a leadership transfer to another replica.
	TransferLeader(context.Context, *TransferLeaderRequest) (*TransferLeaderResponse, error)
	// RequestSnapshot triggers an immediate snapshot of a shard.
	RequestSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// GetNodeHostInfo returns status information for the local NodeHost.
	GetNodeHostInfo(context.Context, *NodeHostInfoRequest) (*NodeHostInfoResponse, error)
	// GetLeader returns the current leader of the specified shard.
	GetLeader(context.Context, *GetLeaderRequest) (*GetLeaderResponse, error)
	// HealthCheck returns OK when the NodeHost is alive and accepting requests.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDragonboatServiceServer()
}

// UnimplementedDragonboatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDragonboatServiceServer struct{}

func (UnimplementedDragonboatServiceServer) Propose(context.Context, *ProposeRequest) (*ProposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedDragonboatServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedDragonboatServiceServer) StaleRead(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StaleRead not implemented")
}
func (UnimplementedDragonboatServiceServer) GetMembership(context.Context, *GetMembershipRequest) (*GetMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembership not implemented")
}
func (UnimplementedDragonboatServiceServer) AddReplica(context.Context, *AddReplicaRequest) (*AddReplicaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddReplica not implemented")
}
func (UnimplementedDragonboatServiceServer) RemoveReplica(context.Context, *RemoveReplicaRequest) (*RemoveReplicaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveReplica not implemented")
}
func (UnimplementedDragonboatServiceServer) TransferLeader(context.Context, *TransferLeaderRequest) (*TransferLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferLeader not implemented")
}
func (UnimplementedDragonboatServiceServer) RequestSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestSnapshot not implemented")
}
func (UnimplementedDragonboatServiceServer) GetNodeHostInfo(context.Context, *NodeHostInfoRequest) (*NodeHostInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeHostInfo not implemented")
}
func (UnimplementedDragonboatServiceServer) GetLeader(context.Context, *GetLeaderRequest) (*GetLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeader not implemented")
}
func (UnimplementedDragonboatServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDragonboatServiceServer) mustEmbedUnimplementedDragonboatServiceServer() {}
func (UnimplementedDragonboatServiceServer) testEmbeddedByValue()                           {}

// UnsafeDragonboatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DragonboatServiceServer will
// result in compilation errors.
type UnsafeDragonboatServiceServer interface {
	mustEmbedUnimplementedDragonboatServiceServer()
}

func RegisterDragonboatServiceServer(s grpc.ServiceRegistrar, srv DragonboatServiceServer) {
	// If the following call panics, it indicates UnimplementedDragonboatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DragonboatService_ServiceDesc, srv)
}

func _DragonboatService_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_StaleRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).StaleRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_StaleRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).StaleRead(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_GetMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).GetMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_GetMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).GetMembership(ctx, req.(*GetMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_AddReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).AddReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_AddReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).AddReplica(ctx, req.(*AddReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_RemoveReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).RemoveReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_RemoveReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).RemoveReplica(ctx, req.(*RemoveReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_TransferLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).TransferLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_TransferLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).TransferLeader(ctx, req.(*TransferLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_RequestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).RequestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_RequestSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).RequestSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_GetNodeHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHostInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).GetNodeHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_GetNodeHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).GetNodeHostInfo(ctx, req.(*NodeHostInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_GetLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).GetLeader(ctx, req.(*GetLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonboatService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonboatServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonboatService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonboatServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DragonboatService_ServiceDesc is the grpc.ServiceDesc for DragonboatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DragonboatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dragonboat.v1.DragonboatService",
	HandlerType: (*DragonboatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _DragonboatService_Propose_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _DragonboatService_Read_Handler,
		},
		{
			MethodName: "StaleRead",
			Handler:    _DragonboatService_StaleRead_Handler,
		},
		{
			MethodName: "GetMembership",
			Handler:    _DragonboatService_GetMembership_Handler,
		},
		{
			MethodName: "AddReplica",
			Handler:    _DragonboatService_AddReplica_Handler,
		},
		{
			MethodName: "RemoveReplica",
			Handler:    _DragonboatService_RemoveReplica_Handler,
		},
		{
			MethodName: "TransferLeader",
			Handler:    _DragonboatService_TransferLeader_Handler,
		},
		{
			MethodName: "RequestSnapshot",
			Handler:    _DragonboatService_RequestSnapshot_Handler,
		},
		{
			MethodName: "GetNodeHostInfo",
			Handler:    _DragonboatService_GetNodeHostInfo_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _DragonboatService_GetLeader_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DragonboatService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dragonboat.proto",
}
