// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: dragonboat.proto

package dbpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProposeRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ShardId uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// command is an opaque byte payload interpreted by the state machine.
	Command []byte `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// timeout_ms overrides the server default timeout (0 = use default).
	TimeoutMs     uint64 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeRequest) Reset() {
	*x = ProposeRequest{}
	mi := &file_dragonboat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeRequest) ProtoMessage() {}

func (x *ProposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeRequest.ProtoReflect.Descriptor instead.
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{0}
}

func (x *ProposeRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ProposeRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProposeRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ProposeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value is the uint64 Result.Value returned by IStateMachine.Update.
	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// data is the optional byte slice returned by IStateMachine.Update.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeResponse) Reset() {
	*x = ProposeResponse{}
	mi := &file_dragonboat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeResponse) ProtoMessage() {}

func (x *ProposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeResponse.ProtoReflect.Descriptor instead.
func (*ProposeResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{1}
}

func (x *ProposeResponse) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ProposeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ShardId uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// query is an opaque byte payload interpreted by the state machine.
	Query         []byte `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	TimeoutMs     uint64 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_dragonboat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ReadRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ReadRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is the opaque bytes returned by IStateMachine.Lookup.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_dragonboat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_dragonboat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{4}
}

func (x *GetMembershipRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type GetMembershipResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigChangeId uint64                 `protobuf:"varint,1,opt,name=config_change_id,json=configChangeId,proto3" json:"config_change_id,omitempty"`
	// nodes maps replica_id -> raft_address for voting replicas.
	Nodes map[uint64]string `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// non_votings maps replica_id -> raft_address for non-voting replicas.
	NonVotings map[uint64]string `protobuf:"bytes,3,rep,name=non_votings,json=nonVotings,proto3" json:"non_votings,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// witnesses maps replica_id -> raft_address for witness replicas.
	Witnesses map[uint64]string `protobuf:"bytes,4,rep,name=witnesses,proto3" json:"witnesses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// removed is the set of replica IDs that have been permanently removed.
	Removed       []uint64 `protobuf:"varint,5,rep,packed,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipResponse) Reset() {
	*x = GetMembershipResponse{}
	mi := &file_dragonboat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipResponse) ProtoMessage() {}

func (x *GetMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipResponse.ProtoReflect.Descriptor instead.
func (*GetMembershipResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{5}
}

func (x *GetMembershipResponse) GetConfigChangeId() uint64 {
	if x != nil {
		return x.ConfigChangeId
	}
	return 0
}

func (x *GetMembershipResponse) GetNodes() map[uint64]string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetMembershipResponse) GetNonVotings() map[uint64]string {
	if x != nil {
		return x.NonVotings
	}
	return nil
}

func (x *GetMembershipResponse) GetWitnesses() map[uint64]string {
	if x != nil {
		return x.Witnesses
	}
	return nil
}

func (x *GetMembershipResponse) GetRemoved() []uint64 {
	if x != nil {
		return x.Removed
	}
	return nil
}

type AddReplicaRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ShardId   uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ReplicaId uint64                 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// target is the RaftAddress (or NodeHostID when gossip is enabled).
	Target         string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	ConfigChangeId uint64 `protobuf:"varint,4,opt,name=config_change_id,json=configChangeId,proto3" json:"config_change_id,omitempty"`
	TimeoutMs      uint64 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddReplicaRequest) Reset() {
	*x = AddReplicaRequest{}
	mi := &file_dragonboat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplicaRequest) ProtoMessage() {}

func (x *AddReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplicaRequest.ProtoReflect.Descriptor instead.
func (*AddReplicaRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{6}
}

func (x *AddReplicaRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *AddReplicaRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *AddReplicaRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AddReplicaRequest) GetConfigChangeId() uint64 {
	if x != nil {
		return x.ConfigChangeId
	}
	return 0
}

func (x *AddReplicaRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type AddReplicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplicaResponse) Reset() {
	*x = AddReplicaResponse{}
	mi := &file_dragonboat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplicaResponse) ProtoMessage() {}

func (x *AddReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplicaResponse.ProtoReflect.Descriptor instead.
func (*AddReplicaResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{7}
}

type RemoveReplicaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShardId        uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ReplicaId      uint64                 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	ConfigChangeId uint64                 `protobuf:"varint,3,opt,name=config_change_id,json=configChangeId,proto3" json:"config_change_id,omitempty"`
	TimeoutMs      uint64                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveReplicaRequest) Reset() {
	*x = RemoveReplicaRequest{}
	mi := &file_dragonboat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReplicaRequest) ProtoMessage() {}

func (x *RemoveReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReplicaRequest.ProtoReflect.Descriptor instead.
func (*RemoveReplicaRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveReplicaRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *RemoveReplicaRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *RemoveReplicaRequest) GetConfigChangeId() uint64 {
	if x != nil {
		return x.ConfigChangeId
	}
	return 0
}

func (x *RemoveReplicaRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type RemoveReplicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReplicaResponse) Reset() {
	*x = RemoveReplicaResponse{}
	mi := &file_dragonboat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReplicaResponse) ProtoMessage() {}

func (x *RemoveReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReplicaResponse.ProtoReflect.Descriptor instead.
func (*RemoveReplicaResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{9}
}

type TransferLeaderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShardId         uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TargetReplicaId uint64                 `protobuf:"varint,2,opt,name=target_replica_id,json=targetReplicaId,proto3" json:"target_replica_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferLeaderRequest) Reset() {
	*x = TransferLeaderRequest{}
	mi := &file_dragonboat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeaderRequest) ProtoMessage() {}

func (x *TransferLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeaderRequest.ProtoReflect.Descriptor instead.
func (*TransferLeaderRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{10}
}

func (x *TransferLeaderRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *TransferLeaderRequest) GetTargetReplicaId() uint64 {
	if x != nil {
		return x.TargetReplicaId
	}
	return 0
}

type TransferLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeaderResponse) Reset() {
	*x = TransferLeaderResponse{}
	mi := &file_dragonboat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeaderResponse) ProtoMessage() {}

func (x *TransferLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeaderResponse.ProtoReflect.Descriptor instead.
func (*TransferLeaderResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{11}
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TimeoutMs     uint64                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_dragonboat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{12}
}

func (x *SnapshotRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *SnapshotRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type SnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// snapshot_index is the Raft log index of the captured snapshot.
	SnapshotIndex uint64 `protobuf:"varint,1,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_dragonboat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{13}
}

func (x *SnapshotResponse) GetSnapshotIndex() uint64 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

type NodeHostInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkipLogInfo   bool                   `protobuf:"varint,1,opt,name=skip_log_info,json=skipLogInfo,proto3" json:"skip_log_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHostInfoRequest) Reset() {
	*x = NodeHostInfoRequest{}
	mi := &file_dragonboat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHostInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHostInfoRequest) ProtoMessage() {}

func (x *NodeHostInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHostInfoRequest.ProtoReflect.Descriptor instead.
func (*NodeHostInfoRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{14}
}

func (x *NodeHostInfoRequest) GetSkipLogInfo() bool {
	if x != nil {
		return x.SkipLogInfo
	}
	return false
}

type ShardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ReplicaId     uint64                 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	IsLeader      bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Nodes         map[uint64]string      `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardInfo) Reset() {
	*x = ShardInfo{}
	mi := &file_dragonboat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfo) ProtoMessage() {}

func (x *ShardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfo.ProtoReflect.Descriptor instead.
func (*ShardInfo) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{15}
}

func (x *ShardInfo) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardInfo) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *ShardInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *ShardInfo) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *ShardInfo) GetNodes() map[uint64]string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeHostInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeHostId    string                 `protobuf:"bytes,1,opt,name=node_host_id,json=nodeHostId,proto3" json:"node_host_id,omitempty"`
	RaftAddress   string                 `protobuf:"bytes,2,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	Shards        []*ShardInfo           `protobuf:"bytes,3,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHostInfoResponse) Reset() {
	*x = NodeHostInfoResponse{}
	mi := &file_dragonboat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHostInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHostInfoResponse) ProtoMessage() {}

func (x *NodeHostInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHostInfoResponse.ProtoReflect.Descriptor instead.
func (*NodeHostInfoResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{16}
}

func (x *NodeHostInfoResponse) GetNodeHostId() string {
	if x != nil {
		return x.NodeHostId
	}
	return ""
}

func (x *NodeHostInfoResponse) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *NodeHostInfoResponse) GetShards() []*ShardInfo {
	if x != nil {
		return x.Shards
	}
	return nil
}

type GetLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderRequest) Reset() {
	*x = GetLeaderRequest{}
	mi := &file_dragonboat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderRequest) ProtoMessage() {}

func (x *GetLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{17}
}

func (x *GetLeaderRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type GetLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      uint64                 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderResponse) Reset() {
	*x = GetLeaderResponse{}
	mi := &file_dragonboat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderResponse) ProtoMessage() {}

func (x *GetLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{18}
}

func (x *GetLeaderResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *GetLeaderResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *GetLeaderResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_dragonboat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{19}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeHostId    string                 `protobuf:"bytes,2,opt,name=node_host_id,json=nodeHostId,proto3" json:"node_host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_dragonboat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dragonboat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_dragonboat_proto_rawDescGZIP(), []int{20}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetNodeHostId() string {
	if x != nil {
		return x.NodeHostId
	}
	return ""
}

var File_dragonboat_proto protoreflect.FileDescriptor

const file_dragonboat_proto_rawDesc = "" +
	"\n" +
	"\x10dragonboat.proto\x12\rdragonboat.v1\x1a\x1cgoogle/api/annotations.proto\"d\n" +
	"\x0eProposeRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\fR\acommand\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x04R\ttimeoutMs\";\n" +
	"\x0fProposeResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"]\n" +
	"\vReadRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\fR\x05query\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x04R\ttimeoutMs\"\"\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"1\n" +
	"\x14GetMembershipRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\"\x83\x04\n" +
	"\x15GetMembershipResponse\x12(\n" +
	"\x10config_change_id\x18\x01 \x01(\x04R\x0econfigChangeId\x12E\n" +
	"\x05nodes\x18\x02 \x03(\v2/.dragonboat.v1.GetMembershipResponse.NodesEntryR\x05nodes\x12U\n" +
	"\vnon_votings\x18\x03 \x03(\v24.dragonboat.v1.GetMembershipResponse.NonVotingsEntryR\n" +
	"nonVotings\x12Q\n" +
	"\twitnesses\x18\x04 \x03(\v23.dragonboat.v1.GetMembershipResponse.WitnessesEntryR\twitnesses\x12\x18\n" +
	"\aremoved\x18\x05 \x03(\x04R\aremoved\x1a8\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fNonVotingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eWitnessesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\x11AddReplicaRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x04R\treplicaId\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12(\n" +
	"\x10config_change_id\x18\x04 \x01(\x04R\x0econfigChangeId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x04R\ttimeoutMs\"\x14\n" +
	"\x12AddReplicaResponse\"\x99\x01\n" +
	"\x14RemoveReplicaRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x04R\treplicaId\x12(\n" +
	"\x10config_change_id\x18\x03 \x01(\x04R\x0econfigChangeId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x04R\ttimeoutMs\"\x17\n" +
	"\x15RemoveReplicaResponse\"^\n" +
	"\x15TransferLeaderRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12*\n" +
	"\x11target_replica_id\x18\x02 \x01(\x04R\x0ftargetReplicaId\"\x18\n" +
	"\x16TransferLeaderResponse\"K\n" +
	"\x0fSnapshotRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x04R\ttimeoutMs\"9\n" +
	"\x10SnapshotResponse\x12%\n" +
	"\x0esnapshot_index\x18\x01 \x01(\x04R\rsnapshotIndex\"9\n" +
	"\x13NodeHostInfoRequest\x12\"\n" +
	"\rskip_log_info\x18\x01 \x01(\bR\vskipLogInfo\"\xf4\x01\n" +
	"\tShardInfo\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x04R\treplicaId\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x04R\bleaderId\x129\n" +
	"\x05nodes\x18\x05 \x03(\v2#.dragonboat.v1.ShardInfo.NodesEntryR\x05nodes\x1a8\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x14NodeHostInfoResponse\x12 \n" +
	"\fnode_host_id\x18\x01 \x01(\tR\n" +
	"nodeHostId\x12!\n" +
	"\fraft_address\x18\x02 \x01(\tR\vraftAddress\x120\n" +
	"\x06shards\x18\x03 \x03(\v2\x18.dragonboat.v1.ShardInfoR\x06shards\"-\n" +
	"\x10GetLeaderRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\"b\n" +
	"\x11GetLeaderResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x04R\bleaderId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\"\x14\n" +
	"\x12HealthCheckRequest\"O\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12 \n" +
	"\fnode_host_id\x18\x02 \x01(\tR\n" +
	"nodeHostId2\xda\n" +
	"\n" +
	"\x11DragonboatService\x12r\n" +
	"\aPropose\x12\x1d.dragonboat.v1.ProposeRequest\x1a\x1e.dragonboat.v1.ProposeResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/shards/{shard_id}/propose\x12f\n" +
	"\x04Read\x12\x1a.dragonboat.v1.ReadRequest\x1a\x1b.dragonboat.v1.ReadResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/shards/{shard_id}/read\x12q\n" +
	"\tStaleRead\x12\x1a.dragonboat.v1.ReadRequest\x1a\x1b.dragonboat.v1.ReadResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/shards/{shard_id}/stale-read\x12\x84\x01\n" +
	"\rGetMembership\x12#.dragonboat.v1.GetMembershipRequest\x1a$.dragonboat.v1.GetMembershipResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/shards/{shard_id}/membership\x12|\n" +
	"\n" +
	"AddReplica\x12 .dragonboat.v1.AddReplicaRequest\x1a!.dragonboat.v1.AddReplicaResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/shards/{shard_id}/replicas\x12\x8f\x01\n" +
	"\rRemoveReplica\x12#.dragonboat.v1.RemoveReplicaRequest\x1a$.dragonboat.v1.RemoveReplicaResponse\"3\x82\xd3\xe4\x93\x02-*+/v1/shards/{shard_id}/replicas/{replica_id}\x12\x8f\x01\n" +
	"\x0eTransferLeader\x12$.dragonboat.v1.TransferLeaderRequest\x1a%.dragonboat.v1.TransferLeaderResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/shards/{shard_id}/transfer-leader\x12}\n" +
	"\x0fRequestSnapshot\x12\x1e.dragonboat.v1.SnapshotRequest\x1a\x1f.dragonboat.v1.SnapshotResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/shards/{shard_id}/snapshot\x12p\n" +
	"\x0fGetNodeHostInfo\x12\".dragonboat.v1.NodeHostInfoRequest\x1a#.dragonboat.v1.NodeHostInfoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/nodehost\x12t\n" +
	"\tGetLeader\x12\x1f.dragonboat.v1.GetLeaderRequest\x1a .dragonboat.v1.GetLeaderResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/shards/{shard_id}/leader\x12f\n" +
	"\vHealthCheck\x12!.dragonboat.v1.HealthCheckRequest\x1a\".dragonboat.v1.HealthCheckResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthzB0Z.github.com/lni/dragonboat/v4/server/proto;dbpbb\x06proto3"

var (
	file_dragonboat_proto_rawDescOnce sync.Once
	file_dragonboat_proto_rawDescData []byte
)

func file_dragonboat_proto_rawDescGZIP() []byte {
	file_dragonboat_proto_rawDescOnce.Do(func() {
		file_dragonboat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dragonboat_proto_rawDesc), len(file_dragonboat_proto_rawDesc)))
	})
	return file_dragonboat_proto_rawDescData
}

var file_dragonboat_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_dragonboat_proto_goTypes = []any{
	(*ProposeRequest)(nil),         // 0: dragonboat.v1.ProposeRequest
	(*ProposeResponse)(nil),        // 1: dragonboat.v1.ProposeResponse
	(*ReadRequest)(nil),            // 2: dragonboat.v1.ReadRequest
	(*ReadResponse)(nil),           // 3: dragonboat.v1.ReadResponse
	(*GetMembershipRequest)(nil),   // 4: dragonboat.v1.GetMembershipRequest
	(*GetMembershipResponse)(nil),  // 5: dragonboat.v1.GetMembershipResponse
	(*AddReplicaRequest)(nil),      // 6: dragonboat.v1.AddReplicaRequest
	(*AddReplicaResponse)(nil),     // 7: dragonboat.v1.AddReplicaResponse
	(*RemoveReplicaRequest)(nil),   // 8: dragonboat.v1.RemoveReplicaRequest
	(*RemoveReplicaResponse)(nil),  // 9: dragonboat.v1.RemoveReplicaResponse
	(*TransferLeaderRequest)(nil),  // 10: dragonboat.v1.TransferLeaderRequest
	(*TransferLeaderResponse)(nil), // 11: dragonboat.v1.TransferLeaderResponse
	(*SnapshotRequest)(nil),        // 12: dragonboat.v1.SnapshotRequest
	(*SnapshotResponse)(nil),       // 13: dragonboat.v1.SnapshotResponse
	(*NodeHostInfoRequest)(nil),    // 14: dragonboat.v1.NodeHostInfoRequest
	(*ShardInfo)(nil),              // 15: dragonboat.v1.ShardInfo
	(*NodeHostInfoResponse)(nil),   // 16: dragonboat.v1.NodeHostInfoResponse
	(*GetLeaderRequest)(nil),       // 17: dragonboat.v1.GetLeaderRequest
	(*GetLeaderResponse)(nil),      // 18: dragonboat.v1.GetLeaderResponse
	(*HealthCheckRequest)(nil),     // 19: dragonboat.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 20: dragonboat.v1.HealthCheckResponse
	nil,                            // 21: dragonboat.v1.GetMembershipResponse.NodesEntry
	nil,                            // 22: dragonboat.v1.GetMembershipResponse.NonVotingsEntry
	nil,                            // 23: dragonboat.v1.GetMembershipResponse.WitnessesEntry
	nil,                            // 24: dragonboat.v1.ShardInfo.NodesEntry
}
var file_dragonboat_proto_depIdxs = []int32{
	21, // 0: dragonboat.v1.GetMembershipResponse.nodes:type_name -> dragonboat.v1.GetMembershipResponse.NodesEntry
	22, // 1: dragonboat.v1.GetMembershipResponse.non_votings:type_name -> dragonboat.v1.GetMembershipResponse.NonVotingsEntry
	23, // 2: dragonboat.v1.GetMembershipResponse.witnesses:type_name -> dragonboat.v1.GetMembershipResponse.WitnessesEntry
	24, // 3: dragonboat.v1.ShardInfo.nodes:type_name -> dragonboat.v1.ShardInfo.NodesEntry
	15, // 4: dragonboat.v1.NodeHostInfoResponse.shards:type_name -> dragonboat.v1.ShardInfo
	0,  // 5: dragonboat.v1.DragonboatService.Propose:input_type -> dragonboat.v1.ProposeRequest
	2,  // 6: dragonboat.v1.DragonboatService.Read:input_type -> dragonboat.v1.ReadRequest
	2,  // 7: dragonboat.v1.DragonboatService.StaleRead:input_type -> dragonboat.v1.ReadRequest
	4,  // 8: dragonboat.v1.DragonboatService.GetMembership:input_type -> dragonboat.v1.GetMembershipRequest
	6,  // 9: dragonboat.v1.DragonboatService.AddReplica:input_type -> dragonboat.v1.AddReplicaRequest
	8,  // 10: dragonboat.v1.DragonboatService.RemoveReplica:input_type -> dragonboat.v1.RemoveReplicaRequest
	10, // 11: dragonboat.v1.DragonboatService.TransferLeader:input_type -> dragonboat.v1.TransferLeaderRequest
	12, // 12: dragonboat.v1.DragonboatService.RequestSnapshot:input_type -> dragonboat.v1.SnapshotRequest
	14, // 13: dragonboat.v1.DragonboatService.GetNodeHostInfo:input_type -> dragonboat.v1.NodeHostInfoRequest
	17, // 14: dragonboat.v1.DragonboatService.GetLeader:input_type -> dragonboat.v1.GetLeaderRequest
	19, // 15: dragonboat.v1.DragonboatService.HealthCheck:input_type -> dragonboat.v1.HealthCheckRequest
	1,  // 16: dragonboat.v1.DragonboatService.Propose:output_type -> dragonboat.v1.ProposeResponse
	3,  // 17: dragonboat.v1.DragonboatService.Read:output_type -> dragonboat.v1.ReadResponse
	3,  // 18: dragonboat.v1.DragonboatService.StaleRead:output_type -> dragonboat.v1.ReadResponse
	5,  // 19: dragonboat.v1.DragonboatService.GetMembership:output_type -> dragonboat.v1.GetMembershipResponse
	7,  // 20: dragonboat.v1.DragonboatService.AddReplica:output_type -> dragonboat.v1.AddReplicaResponse
	9,  // 21: dragonboat.v1.DragonboatService.RemoveReplica:output_type -> dragonboat.v1.RemoveReplicaResponse
	11, // 22: dragonboat.v1.DragonboatService.TransferLeader:output_type -> dragonboat.v1.TransferLeaderResponse
	13, // 23: dragonboat.v1.DragonboatService.RequestSnapshot:output_type -> dragonboat.v1.SnapshotResponse
	16, // 24: dragonboat.v1.DragonboatService.GetNodeHostInfo:output_type -> dragonboat.v1.NodeHostInfoResponse
	18, // 25: dragonboat.v1.DragonboatService.GetLeader:output_type -> dragonboat.v1.GetLeaderResponse
	20, // 26: dragonboat.v1.DragonboatService.HealthCheck:output_type -> dragonboat.v1.HealthCheckResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dragonboat_proto_init() }
func file_dragonboat_proto_init() {
	if File_dragonboat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dragonboat_proto_rawDesc), len(file_dragonboat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dragonboat_proto_goTypes,
		DependencyIndexes: file_dragonboat_proto_depIdxs,
		MessageInfos:      file_dragonboat_proto_msgTypes,
	}.Build()
	File_dragonboat_proto = out.File
	file_dragonboat_proto_goTypes = nil
	file_dragonboat_proto_depIdxs = nil
}
